folder_name: "blip2ft5xl_calibrated_vlm/"
exp_name: "tulu2_7b_qgen-flant5xl_llm-lvis_objdet"

qgen:
  class_name: "tulu"
  model_config_path: "configs/qgen_configs/tulu2_7b-verifying_prompt_detailed.yaml"

llm:
  class_name: "t5"
  model_config_path: "configs/llm_configs/flant5xl.yaml"

vlm:
  class_name: "blip"
  model_config_path: "configs/vlm_configs/blip2_flant5xl.yaml"
  caption_inference_params:
    num_beams: 5
    max_length: 30
    length_penalty: 2.0
    repetition_penalty: 10.0
    return_dict_in_generate: True
    output_scores: True
  vqa_inference_params:
    num_beams: 5
    length_penalty: -1.0
    return_dict_in_generate: True
    output_scores: True
  use_confidence_calibrator: True
  calibrator_model_path: "/net/nfs.cirrascale/mosaic/tejass/experiments/vl_calibration/calibration_model/calibrated_blip2flant5xl-aokvqa_direct_answer-calibration_clf.pkl"

objdet:
  class_name: "lvis"
  model_config_path: "configs/objdet_configs/lvis.yaml"

regcapdb:
  class_name: "qwenvl"
  model_config_path: "configs/regcapdb_configs/qwenvl_regioncaps_aokvqa_val.yaml"

recoverr:
  do_recoverr: True
  max_evidence_collection_turns: 10
  questions_generated_per_turn: 10
  desired_risk: 0.1 # 0.1, 0.2
  vqaconfthresh_at_risk: 0.73 # 0.86, 0.73
  min_entailment_conf: 0.9
  defeasibility_delta: 0.2
  visual_tools: ['imcap', 'objdet']
  