folder_name: "calibrated_llavaplus7b_vlm/chatgpt_qgen-flant5xl_llm"
exp_name: "lvis_objdet-qwenvl_regcap-verifying_prompt_detailed"

qgen:
  class_name: "gpt"
  model_config_path: "/home/tejas/projects/ReCoVERR/configs/qgen_configs/chatgpt-verifying_prompt_detailed.yaml"

llm:
  class_name: "t5"
  model_config_path: "/home/tejas/projects/ReCoVERR/configs/llm_configs/flant5xl.yaml"

vlm:
  class_name: "llava"
  model_config_path: "/home/tejas/projects/ReCoVERR/configs/vlm_configs/llava_1.5_7b.yaml"
  caption_inference_params:
    num_beams: 5
    max_length: 30
    length_penalty: 2.0
    repetition_penalty: 10.0
    return_dict_in_generate: True
    output_scores: True
  vqa_inference_params:
    num_beams: 5
    length_penalty: -1
    max_new_tokens: 10
    return_dict_in_generate: True
    output_scores: True
  use_confidence_calibrator: True
  calibrator_model_path: "/home/tejas/experiments/recoverr/vl_calibration/calibration_model/calibrated_llavaplus7b-aokvqa_direct_answer-calibration_clf.pkl"

objdet:
  class_name: "lvis"
  model_config_path: "/home/tejas/projects/ReCoVERR/configs/objdet_configs/lvis.yaml"

regcapdb:
  class_name: "qwenvl"
  model_config_path: "/home/tejas/projects/ReCoVERR/configs/regcapdb_configs/qwenvl_regioncaps_aokvqa_val.yaml"

recoverr:
  do_recoverr: True
  max_evidence_collection_turns: 10
  questions_generated_per_turn: 10
  desired_risk: 0.2   # 0.2
  vqaconfthresh_at_risk: 0.69  # 0.69
  min_entailment_conf: 0.9
  defeasibility_delta: 0.2
  visual_tools: ['imcap', 'objdet', 'regcapdb']
  