folder_name: "tool_use_baselines/uncalibrated_llavaplus7b-meantokenprob_conf"
exp_name: "lvis_objdet-qwenvl_regcap"

qgen:
  class_name: "gpt"
  model_config_path: "configs/qgen_configs/chatgpt-verifying_prompt_detailed.yaml"

llm:
  class_name: "t5"
  model_config_path: "configs/llm_configs/flant5xl.yaml"

vlm:
  class_name: "llava"
  model_config_path: "configs/vlm_configs/llava_1.5_7b.yaml"
  caption_inference_params:
    num_beams: 5
    max_length: 30
    length_penalty: 2.0
    repetition_penalty: 10.0
    return_dict_in_generate: True
    output_scores: True
  vqa_inference_params:
    num_beams: 5
    length_penalty: -1
    max_new_tokens: 10
    return_dict_in_generate: True
    output_scores: True
  use_confidence_calibrator: False

objdet:
  class_name: "lvis"
  model_config_path: "configs/objdet_configs/lvis.yaml"

regcapdb:
  class_name: "qwenvl"
  model_config_path: "configs/regcapdb_configs/qwenvl_regioncaps_aokvqa_val.yaml"

recoverr:
  do_recoverr: False
  vlm_conf_type: "mean_token_prob"
  max_evidence_collection_turns: 10
  questions_generated_per_turn: 10
  desired_risk: 0.2   # 0.1, 0.2
  vqaconfthresh_at_risk: 0.63  # 0.84, 0.63
  min_entailment_conf: 0.9
  defeasibility_delta: 0.2
  visual_tools: ['imcap', 'objdet']
  