exp_name: "chatgpt_qgen-flant5xl_llm-blip2ft5xl_vlm-detr_objdet-verifying_prompt_detailed"

qgen:
  class_name: "gpt"
  model_config_path: "/net/nfs.cirrascale/mosaic/tejass/code/ReCoVERR/configs/qgen_configs/chatgpt-verifying_prompt_detailed.yaml"

llm:
  class_name: "t5"
  model_config_path: "/net/nfs.cirrascale/mosaic/tejass/code/ReCoVERR/configs/llm_configs/flant5xl.yaml"

vlm:
  class_name: "blip"
  model_config_path: "/net/nfs.cirrascale/mosaic/tejass/code/ReCoVERR/configs/vlm_configs/blip2_flant5xl.yaml"
  caption_inference_params:
    max_length: 30
    length_penalty: 2.0
    repetition_penalty: 10.0
    return_dict_in_generate: True
    output_scores: True
  vqa_inference_params:
    num_beams: 5
    length_penalty: -1.0
    return_dict_in_generate: True
    output_scores: True
  use_confidence_calibrator: False

objdet:
  class_name: "detr"
  model_config_path: "/net/nfs.cirrascale/mosaic/tejass/code/ReCoVERR/configs/objdet_configs/detr.yaml"

recoverr:
  max_evidence_collection_turns: 10
  questions_generated_per_turn: 10
  desired_risk: 0.2
  vqaconfthresh_at_risk: 0.82
  min_entailment_conf: 0.9
  defeasibility_delta: 0.2
  