folder_name: "instructblipft5xl_calibrated_vlm/"
exp_name: "chatgpt_qgen-flant5xl_llm-lvis_objdet"

qgen:
  class_name: "gpt"
  model_config_path: "configs/qgen_configs/chatgpt-verifying_prompt_detailed.yaml"

llm:
  class_name: "t5"
  model_config_path: "configs/llm_configs/flant5xl.yaml"

vlm:
  class_name: "blip"
  model_config_path: "configs/vlm_configs/instructblip_flant5xl.yaml"
  caption_inference_params:
    num_beams: 5
    max_length: 30
    length_penalty: 2.0
    repetition_penalty: 10.0
    return_dict_in_generate: True
    output_scores: True
  vqa_inference_params:
    num_beams: 5
    length_penalty: -1.0
    return_dict_in_generate: True
    output_scores: True
  use_confidence_calibrator: True
  calibrator_model_path: "/net/nfs.cirrascale/mosaic/tejass/experiments/vl_calibration/calibration_model/calibrated_instructblipflant5xl-aokvqa_direct_answer-calibration_clf.pkl"

objdet:
  class_name: "lvis"
  model_config_path: "configs/objdet_configs/lvis.yaml"

recoverr:
  do_recoverr: True
  max_evidence_collection_turns: 10
  questions_generated_per_turn: 10
  desired_risk: 0.2 # 0.1, 0.2
  vqaconfthresh_at_risk: 0.65 # 0.65, 0.83
  min_entailment_conf: 0.9
  defeasibility_delta: 0.2
  visual_tools: ['imcap', 'objdet']
  