imcapdb_display_name: 'Qwen-VL-Chat-RegionCaptions'
region_captions_file: '/net/nfs.cirrascale/mosaic/tejass/data/a-okvqa/preprocd_data/qwen_verbalizations/coco_val_samregions_qwenregioncaptions.jsonl'
