model_class: "llava"
model_shorthand: "llava_1.5_7b"
model_display_name: "LLaVA-1.5-7B"
pt_model_name: "llava-hf/llava-1.5-7b-hf"
vqa_inference_params:
  num_beams: 5
  length_penalty: -1.0
  return_dict_in_generate: True
  output_scores: True